### How to use this document
# 1. Fill in your info
# 2. Re-excecute the build in the command line with: bundle exec jekyll serve
# 3. Push to github
# NOTE: it looks like you need to rebuild + repush everytime you update this _config.yml file

### Site Settings ###
title: "Jingjing Liang's personal website"
description: >
  I am Jingjing Liang, <br>
  you can also call me Marie!
baseurl: ""  
repository: "xenotopia/xenotopia.github.io"
open_new_tab: false

### Plugins ###
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - mini_magick

### To specify which port to host locally on -- use if you have multiple sites you want to host 
port: 4008

### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**

### Author Info ###
author:
  name: "Jingjing Liang"
  image: "https://xenotopia.github.io/image/IMG_2037.jpeg"
  email: "marieliang796@gmail.com"
  github: "marieliang796/xenotopia"
  instagram: "marieliang_"
  linkedin: "marie-jingjing-liang-897890284"

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:
    output: true

### Disqus ###
disqus:
  shortname: your-short-name-disqus

### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id

### Buy me a coffee ###
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."
  description: "Support me on Buy me a coffee!"

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "elements"
    values:
      layout: "element"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

### Exclude from processing ###
exclude:
  - README.md
  - README.md~
  - CONTRIBUTING.md
  - LICENSE.md
  - LICENSE.md~
  - config.yml~
  - "*.log"
  - "*.ipynb"
  - "python_notebooks/*"
